#ifndef _IOCTL_BUZZER_H_
#define _IOCTL_BUZZER_H_

#define IOCTL_BUZZER_MAGIC                  'b'
#define SUCCESS_SOUND_BUZZER                0
#define BUTTON_PUSH_SOUND_BUZZER            1

#define IOCTL_CMD_SUCCESS_SOUND_BUZZER      _IO(IOCTL_BUZZER_MAGIC, SUCCESS_SOUND_BUZZER)
#define IOCTL_CMD_BUTTON_PUSH_SOUND_BUZZER  _IO(IOCTL_BUZZER_MAGIC, BUTTON_PUSH_SOUND_BUZZER)
 
#define IOCTL_MAXNR_BUZZER                  2
  
#endif
