#!/bin/sh

[ -f /etc/config/core_config.yaml ] || exit 0

case "$1" in
        start)
                printf "Starting core: "
                start-stop-daemon -S -x /usr/bin/core -f /etc/config/core_config.yaml
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        stop)
                printf "Stopping core: "
                start-stop-daemon -K -q -x /usr/bin/core
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit 0
