DRIVERS:
  BUZZER_PATH: /dev/buzzer
  OLED_PATH: /dev/oled
  KEYPAD_PATH: /dev/keyPad
MQTT:
  BROKER_URL: 192.168.219.103:1883
  PUB_TOPIC_NAME: /home/door
  SUB_TOPIC_NAME: /home/access
  CLI_ID: bsoh
  QOS: 1
  INTERVAL: 20
  TIME_OUT: 1000
THREAD_POOL:
  NUM: 3
VIDEO:
  READ_PATH: /dev/video0
  DEST_IP: 192.168.219.106
  DEST_PORT: 18080
  IMG_WIDTH: 400
  IMG_HEIGHT: 240
SYSTEM:
  PW: ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f
  SALT: 5678
  MAX_PW: 5
